require 'rake'
require 'fileutils'

task :default => [:clean, :build]

desc "Clean files"
task :clean do
  recreate_folder "build"
end

desc "Compile document"
task :build do
	pdflatex "session.tex", "build"
end

def recreate_folder(folder)
  puts "Recreating folder: #{folder}..."
  FileUtils.rm_rf folder
  FileUtils.mkdir folder
end

def pdflatex(tex_file, into_folder)
  pdf_file = tex_file.gsub('.tex', '.pdf')
  file_to_publish = "#{ File.basename(Dir.getwd) }.pdf"
  
  puts "Processing file: #{tex_file}"
  system "pdflatex -output-directory #{into_folder} #{tex_file} 1> /dev/null"

  FileUtils.cp "#{into_folder}/#{pdf_file}", "#{into_folder}/#{file_to_publish}"
  puts "Please publish file: #{into_folder}/#{file_to_publish}"
end