require 'rake'
require 'fileutils'

task :default => [:clean, :build, :dist]

PROJECT_NAME = File.basename(Dir.getwd)
BUILD_FOLDER = 'build'
DIST_FOLDER = 'dist'

desc "Clean files"
task :clean do
  recreate BUILD_FOLDER
  recreate DIST_FOLDER
end

desc "Compile documents"
task :build => [:presentation, :notes]

task :presentation => [:clean] do
	pdflatex 'session.presentation.tex', BUILD_FOLDER
end

task :notes => [:clean] do
	pdflatex 'session.notes.tex', BUILD_FOLDER
end

desc "Prepare documents for distribution"
task :dist => [:clean, :build] do
  copy_as "#{DIST_FOLDER}/#{PROJECT_NAME}.pdf", "#{BUILD_FOLDER}/session.presentation.pdf"
  copy_as "#{DIST_FOLDER}/#{PROJECT_NAME}.notes.pdf", "#{BUILD_FOLDER}/session.notes.pdf"
end

desc "Open presentation document"
task :open => :open_presentation

task :open_presentation => [:dist] do
  open_at DIST_FOLDER, "#{PROJECT_NAME}.pdf"
end

desc "Open notes document"
task :open_notes => [:dist] do
  open_at DIST_FOLDER, "#{PROJECT_NAME}.notes.pdf"
end


private

def recreate(folder)
  puts "Recreating folder: #{folder}..."
  FileUtils.rm_rf folder
  FileUtils.mkdir folder
end

def copy_as(target, source)
  puts "Copying as #{target} file #{source}"
  FileUtils.cp source, target
end

def pdflatex(tex_file, into)
  puts "Processing file: #{tex_file}"
  `pdflatex -output-directory #{into} #{tex_file}`
end

def open_at(folder, file)
  system "open #{folder}/#{file}"
end