require 'rake'
require 'fileutils'

task :default => :dist

PROJECT_NAME = File.basename(Dir.getwd)
BUILD_FOLDER = 'build'
DIST_FOLDER = 'dist'

desc "Clean folders"
task :clean do
  delete BUILD_FOLDER, DIST_FOLDER
end

desc "Create folders"
task :init => [:clean] do
  create BUILD_FOLDER, DIST_FOLDER
end

desc "Compile documents"
task :build  => [:init] do
	pdflatex 'session.presentation.tex', BUILD_FOLDER
	pdflatex 'session.notes.tex', BUILD_FOLDER
	pdflatex 'session.with_notes.tex', BUILD_FOLDER
end

desc "Prepare documents for distribution"
task :dist => [:init, :build] do
  copy_as "#{DIST_FOLDER}/#{PROJECT_NAME}.pdf", "#{BUILD_FOLDER}/session.presentation.pdf"
  copy_as "#{DIST_FOLDER}/#{PROJECT_NAME}.notes.pdf", "#{BUILD_FOLDER}/session.notes.pdf"
  copy_as "#{DIST_FOLDER}/#{PROJECT_NAME}.with_notes.pdf", "#{BUILD_FOLDER}/session.with_notes.pdf"
end

desc "Open presentation document"
task :open => :open_presentation

task :open_presentation => [:dist] do
  open_at DIST_FOLDER, "#{PROJECT_NAME}.pdf"
end

desc "Open notes document"
task :open_notes => [:dist] do
  open_at DIST_FOLDER, "#{PROJECT_NAME}.notes.pdf"
end

private

def delete(*folders)
  folders.each do |folder|
    puts "Deleting #{folder}..."
    FileUtils.rm_rf folder
  end
end

def create(*folders)
  folders.each do |folder|
    puts "Creating #{folder}..."
    FileUtils.mkdir folder
  end
end

def copy_as(target, source)
  puts "Copying as #{target} file #{source}"
  FileUtils.cp source, target
end

def pdflatex(tex_file, into)
  puts "Processing file: #{tex_file}"
  `pdflatex -output-directory #{into} #{tex_file}`
end

def open_at(folder, file)
  system "open #{folder}/#{file}"
end