require 'rake'
require 'fileutils'

task :default => [:clean, :build]

desc "Clean files"
task :clean do
	delete %w[ *.aux *.log *.nav *.out *.pdf *.snm *.toc ]
end

desc "Compile document"
task :build do
	tex_file = "ExtremeProjectEvaluation.tex"
	system "pdflatex #{tex_file} 1> /dev/null"
end

def delete(items)
	FileUtils.rm_rf items.collect { |each| Dir.glob(each) }
end
